---
- hosts: localhost
  gather_facts: no
  vars:
    var1: "local variable"

  tasks:
  - name: set facts
    set_fact:
      var1: "{{ var1 }}"

  - name: display vars
    debug:
      var: hostvars[inventory_hostname]["var1"]

  - name: display vars
    debug:
      var: hostvars["localhost"]["var1"]

- hosts: mgmt
  gather_facts: no
  vars:
    var1: '{{ hostvars["localhost"]["var1"] }}'
  
  tasks:
  - name: display vars
    debug:
      var: hostvars["localhost"]["var1"]

  - name: display vars
    debug:
      var: hostvars["mgmt"]["var1"]

  - name: display vars
    debug:
      var: var1


